export const cottages = [
  {
    id: 'cove',
    name: 'Cove',
    price: 2000,
    priceLabel: 'PHP 2,000',
    paxMin: 10,
    paxMax: 15,
    paxLabel: '10-15 pax',
    description: 'Recommended for small group day tours and intimate gatherings.',
    details: [
      'Capacity: 10-15 persons with comfortable seating and dining areas.',
      'Amenities: Equipped with sturdy tables and chairs, ceiling fan for shade and cooling.',
      'Features: Cozy atmosphere, perfect for relaxing in a quiet corner of the resort.',
      'Grilling is allowed once this cottage is rented — great for BBQ gatherings.',
      'Restroom facilities: Private and accessible, located near the cottage.',
      'Best choice for groups that want a shaded rest area near common facilities.',
      'Ideal for: Corporate small groups, family reunions, birthday celebrations (small parties).',
    ],
  },
  {
    id: 'jungle',
    name: 'Jungle',
    price: 1800,
    priceLabel: 'PHP 1,800',
    paxMin: 10,
    paxMax: 15,
    paxLabel: '10-15 pax',
    description: 'Value-friendly option excellent for group outings and budget-conscious travelers.',
    details: [
      'Capacity: 10-15 persons with functional tables and chairs.',
      'Amenities: Natural shade from native trees, ceiling fan, open-air design for fresh air flow.',
      'Features: Immersive nature experience with lush surroundings, peaceful environment.',
      'Grilling is allowed once this cottage is rented — perfect for team building BBQs.',
      'Restroom facilities: Convenient access to main resort facilities.',
      'Suitable for barkada and family groups with a similar pax range.',
      'Ideal for: Group outings, team building activities, casual family gatherings, barkada reunions.',
    ],
  },
  {
    id: 'cliffside',
    name: 'Cliffside',
    price: 3500,
    priceLabel: 'PHP 3,500',
    paxMin: 20,
    paxMax: 30,
    paxLabel: '20-30 pax',
    description: 'Best for larger gatherings, celebrations, and special events.',
    details: [
      'Capacity: 20-30 persons with ample space for dining and mingling.',
      'Amenities: Multiple tables and chair sets, panoramic views, elevated seating for scenic vantage point.',
      'Features: Spacious setup ideal for events, natural lighting, breeze-friendly location.',
      'Grilling is allowed once this cottage is rented — premium setup for larger BBQ events.',
      'Restroom facilities: Easy access with adequate facilities for group size.',
      'Spacious setup for groups needing bigger shared space and movement.',
      'Ideal for: Company celebrations, weddings (small reception), large family events, milestone parties.',
    ],
  },
]

export const infoContentByTab = {
  daytour: {
    heading: 'Reminders and General Details',
    reminders: [
      'No early check-in.',
      'No speakers, loud music, or karaoke.',
      'Pets are not allowed.',
      'Tent setups are not permitted (no campsite available).',
      'No kitchen access for day tour guests.',
      'Cooking and grilling are not allowed (grilling is only allowed when a cottage is purchased).',
    ],
    details: [
      'Day tour hours: 8:00 AM to 5:00 PM.',
      'Walk-ins are welcome, subject to availability.',
      'Corkage fee: PHP 50 per person for outside food and drinks.',
      'Food and drinks are also available on-site.',
    ],
  },
  overnight: {
    heading: 'Overnight Reminders and Details',
    reminders: [
      'Check-in and check-out schedules apply by room/cottage type.',
      'Quiet hours are strictly observed for all overnight guests.',
      'Guest count should match your confirmed reservation.',
      'Outside appliances and cooking setups are not allowed unless approved.',
      'Any additional guest is subject to capacity and extra charge policy.',
    ],
    details: [
      'Overnight bookings are reservation-based and subject to room availability.',
      'Package inclusions vary depending on selected overnight offer.',
      'Weekend and holiday rates may differ from weekday rates.',
      'Food and drink options are available on-site.',
    ],
  },
  addons: {
    heading: 'Add-Ons Notes and Details',
    reminders: [
      'Add-ons are subject to availability on your selected date.',
      'Some add-ons require advance reservation and confirmation.',
      'Add-ons may have separate capacity or usage limits.',
      'Add-ons are non-transferable once confirmed.',
    ],
    details: [
      'Add-ons are optional and can be combined with day tour or overnight bookings.',
      'Rates for add-ons are charged on top of your selected package.',
      'Final add-on list and rates are confirmed during reservation processing.',
      'On-site staff can assist with recommended add-ons for your group size.',
    ],
  },
}

export const overnightOffers = [
  {
    id: 'overnight-cottage-stay',
    title: 'Overnight Cottage Stay',
    price: 2000,
    priceLabel: 'From PHP 2,000',
    description: 'Ideal for guests who want a private stay space with overnight access.',
    details: [
      'Choose from Cove, Jungle, or Cliffside cottages based on group size.',
      'Check-in: 2:00 PM | Check-out: 11:00 AM (flexible with prior coordination).',
      'Cottage amenities: Tables, chairs, fan, and access to all resort facilities.',
      'Sleeping arrangements: Bring your own tents, sleeping bags, or use alternative accommodations on-site.',
      'Bathroom access: Clean, accessible restroom facilities available 24/7.',
      'Grilling allowed with cottage reservation — perfect for evening dinners and bonding.',
      'Quiet hours: 11:00 PM to 6:00 AM — please respect the peace of other guests.',
      'Food and beverages available on-site; bring your own is also permitted (corkage fee: PHP 50 per person).',
      'Ideal for: Family overnight trips, barkada trips, corporate retreats, adventure groups.',
      'Best for group sizes: 10-30 persons depending on chosen cottage.',
    ],
  },
  {
    id: 'overnight-family-package',
    title: 'Overnight Family Package',
    price: 3500,
    priceLabel: 'From PHP 3,500',
    description: 'Designed for family groups with bundled overnight inclusions.',
    details: [
      'Includes: Cottage rental, welcome refreshments (juice/coffee), and breakfast spread the next morning.',
      'Group size: Recommended for 10-20 persons (smaller family groups).',
      'Cottage options: Cove or Jungle cottage (spacious and family-friendly).',
      'Sleeping options: Tent packages or indoor accommodation arrangements available upon request.',
      'Evening activities: Bonfire gathering area, lawn games, acoustic music sessions.',
      'Morning breakfast: Simple Filipino-style spread (rice, eggs, local dishes, fresh fruit).',
      'Check-in: 2:00 PM | Check-out: 12:00 PM (next day).',
      'Grilling and cooking allowed with cottage rental — family meals included with planning.',
      'Special requests: Children discounts and family rates available; ask our team for specifics.',
      'Perfect for: Family reunions, milestone celebrations, bonding trips, multi-family get-togethers.',
    ],
  },
  {
    id: 'overnight-barkada-package',
    title: 'Overnight Barkada Package',
    price: 4000,
    priceLabel: 'From PHP 4,000',
    description: 'Best for friends looking for an extended resort stay.',
    details: [
      'Includes: Cottage rental, lunch spread on day of arrival, and grilling station setup.',
      'Group size: Perfect for 15-30 persons (larger friend groups and celebrations).',
      'Cottage options: Jungle or Cliffside cottage for maximum space and fun.',
      'Sleeping arrangements: Tent camping or dormitory-style indoor options available.',
      'Lunch spread: Grilled specialties, rice, vegetables, local side dishes, and beverages.',
      'Evening entertainment: Grilling area fully equipped, videoke available as add-on, games lawn access.',
      'Check-in: 1:00 PM | Check-out: 11:00 AM (next day) — flexible timing with coordination.',
      'Overnight activities: Lawn games, bonfire (seasonal), group dining, stargazing.',
      'Special perks: Group price applied to all attendees; early birthday discounts if applicable.',
      'Perfect for: Birthday bashes, friendship anniversaries, post-season celebrations, bachelor/bachelorette events.',
    ],
  },
]

export const addOns = [
  {
    id: 'extra-table-chair-set',
    title: 'Extra Table and Chair Set',
    price: 300,
    priceLabel: 'PHP 300 per set',
    description: 'Additional seating setup for bigger groups.',
    details: [
      'Quantity: 1 set includes 1 sturdy table and 4-6 chairs.',
      'Perfect for: Extra dining space, kids area, or beverage station setup.',
      'Setup: Our staff will arrange at your preferred cottage location.',
      'Number to order: Calculate based on your group size — 1 set per 4-6 persons recommended.',
      'Great add-on for: Larger gatherings, multiple activity stations, family meals.',
      'Available for: Day tours and overnight packages.',
      'Booking note: Order at least 1 day in advance for availability confirmation.',
    ],
  },
  {
    id: 'grilling-setup-addon',
    title: 'Grilling Setup Add-On',
    price: 800,
    priceLabel: 'PHP 800 per setup',
    description: 'Available when paired with an eligible cottage booking.',
    details: [
      'Includes: Professional grilling station setup with grill, charcoal, and cooking utensils.',
      'Grilling attendant: Available for first 2 hours of setup to guide basic use (additional hours: PHP 200/hour).',
      'Best for groups: 15+ persons where BBQ is the main event.',
      'Duration: Full access during your cottage rental period.',
      'Fuel provided: Charcoal included; additional charcoal available for purchase (PHP 150).',
      'Setup location: Arranged at your cottage or approved grilling zone.',
      'Cooking materials: Bring your own meat/seafood or inquire about on-site sources.',
      'Perfect for: BBQ celebrations, team building BBQs, family feasts, feast celebrations.',
      'Note: Grilling only allowed with cottage rental; not available for basic day tour entrance fee.',
    ],
  },
  {
    id: 'floating-table',
    title: 'Floating Table',
    price: 500,
    priceLabel: 'PHP 500 per day',
    description: 'Great for photos, snacks, and lounge moments.',
    details: [
      'Type: Scenic floating platform setup in designated water area (subject to weather conditions).',
      'Perfect for: Instagram-worthy photos, intimate snack moments, group lounging.',
      'Capacity: 6-10 persons per floating table (standing/light seating).',
      'Duration: Available during operating hours with safety supervision.',
      'Life vests: Provided for all users (complementary).',
      'Setup time: 15-30 minutes upon request; advance booking highly recommended.',
      'Best for: Milestone celebrations, couple photo sessions, group lounging moments.',
      'Weather dependent: Availability subject to water conditions and weather forecast.',
      'Book with: 1 day advance notice; same-day requests subject to availability.',
    ],
  },
  {
    id: 'videoke-sound-addon',
    title: 'Videoke / Sound Add-On',
    price: 1200,
    priceLabel: 'PHP 1,200 for 4 hours | PHP 2,000 for 8 hours',
    description: 'Available in approved areas and time slots.',
    details: [
      'Equipment: Professional-grade videoke machine, 2 microphones, large LED display, full sound system.',
      'Song library: 10,000+ songs (OPM, Pop, Rock, Classics, and more) — requests accepted during event.',
      'Technician: Professional operator available to manage equipment and assist with song selection.',
      'Setup location: Available in Cliffside cottage area; requestable for other locations.',
      'Time slots: 10:00 AM - 9:00 PM (adjust per group needs and operator availability).',
      'Quiet hours: Equipment usage required to stop by 9:00 PM to respect other guests.',
      'Power supply: Provided by resort; outdoor weatherproofing available.',
      'Best for: Birthday parties, celebrations, family karaoke nights, barkada singing contests.',
      'Advance booking: Required — book with at least 2 days notice for operator confirmation.',
      'Add-on pricing: In addition to cottage or day tour package charges.',
    ],
  },
]
